apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sagemcp.fullname" . }}-backend
  labels:
    {{- include "sagemcp.backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sagemcp.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.backend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "sagemcp.backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sagemcp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-db
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h {{ include "sagemcp.postgresql.host" . }} -p {{ include "sagemcp.postgresql.port" . }} -U {{ include "sagemcp.postgresql.username" . }}; do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done
        - name: wait-for-redis
          image: redis:7-alpine
          command:
            - sh
            - -c
            - |
              until redis-cli -h {{ include "sagemcp.redis.host" . }} -p {{ include "sagemcp.redis.port" . }} -a "$REDIS_PASSWORD" ping; do
                echo "Waiting for Redis..."
                sleep 2
              done
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sagemcp.redis.secretName" . }}
                  key: redis-password
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          env:
            - name: DEBUG
              value: {{ .Values.backend.env.DEBUG | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.backend.env.ENVIRONMENT | quote }}
            - name: HOST
              value: {{ .Values.backend.env.HOST | quote }}
            - name: PORT
              value: {{ .Values.backend.env.PORT | quote }}
            - name: DATABASE_URL
              value: {{ include "sagemcp.postgresql.connectionString" . | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sagemcp.postgresql.secretName" . }}
                  key: password
            - name: REDIS_URL
              value: {{ include "sagemcp.redis.connectionString" . | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sagemcp.redis.secretName" . }}
                  key: redis-password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "sagemcp.fullname" . }}-secret
                  key: secret-key
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sagemcp.fullname" . }}-config
                  key: base-url
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sagemcp.fullname" . }}-config
                  key: frontend-url
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sagemcp.fullname" . }}-config
                  key: access-token-expire-minutes
            - name: REFRESH_TOKEN_EXPIRE_DAYS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sagemcp.fullname" . }}-config
                  key: refresh-token-expire-days
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "sagemcp.fullname" . }}-secret
                  key: github-client-id
                  optional: true
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "sagemcp.fullname" . }}-secret
                  key: github-client-secret
                  optional: true
            - name: SLACK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "sagemcp.fullname" . }}-secret
                  key: slack-client-id
                  optional: true
            - name: SLACK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "sagemcp.fullname" . }}-secret
                  key: slack-client-secret
                  optional: true
            - name: MCP_SERVER_TIMEOUT
              value: {{ .Values.backend.env.MCP_SERVER_TIMEOUT | quote }}
            - name: MCP_MAX_CONNECTIONS_PER_TENANT
              value: {{ .Values.backend.env.MCP_MAX_CONNECTIONS_PER_TENANT | quote }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
