apiVersion: v1
kind: Service
metadata:
  name: {{ include "sagemcp.fullname" . }}-frontend
  labels:
    {{- include "sagemcp.frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sagemcp.frontend.selectorLabels" . | nindent 4 }}
